server:
  port: 9527

spring:
   application:
    name: microservicecloud-getway
  
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
#      defaultZone: http://localhost:7001/eureka  单机版
       defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/     #集群
  instance:
    instance-id: getway-9527.com     #自定义服务信息名称
    prefer-ip-address: true #访问路径可以显示ip地址
    
zuul:
  prefix: /atguigu
  ignored-services: "*"                        #microservicecloud-dept
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**    
    
    #注册中心的info信息
info:
  app.name: atguigu-microservicecloud
  company.name: www.atguigu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$      